// Generates shared/src/utils/constants/worldMap.js: every country's outline
// as an SVG path (keyed by ISO code) on a Natural Earth projection, from
// Natural Earth's public domain 1:50m data, simplified to stay light. Tiny
// countries also get a dot, so a visit to Andorra or Malta can be seen.
//
// Its tools aren't project dependencies: to regenerate the map, copy this
// file into an empty folder and there run
//   npm i world-atlas@2 topojson-client@3 topojson-simplify@3 d3-geo@3 i18n-iso-countries@7
//   node generateWorldMap.mjs path/to/shared/src/utils/constants/worldMap.js
import fs from 'fs';
import { createRequire } from 'module';
import { feature } from 'topojson-client';
import { presimplify, quantile, simplify } from 'topojson-simplify';
import { geoCentroid, geoNaturalEarth1, geoPath } from 'd3-geo';
import countries from 'i18n-iso-countries';

const OUTPUT = process.argv[2];
if (!OUTPUT) throw new Error('Pass the path of worldMap.js to write');

const WIDTH = 1000;
const ANTARCTICA = '010';
// Share of the outline points kept: enough to recognise every coastline.
const KEEP_QUANTILE = 0.12;
// Below this projected area (in map units) a country gets a dot.
const TINY_AREA = 20;
const round = (value) => Math.round(value * 10) / 10;

const topologyPath = createRequire(import.meta.url).resolve('world-atlas/countries-50m.json');
const topology = presimplify(JSON.parse(fs.readFileSync(topologyPath, 'utf8')));
const simplified = simplify(topology, quantile(topology, KEEP_QUANTILE));
const all = feature(simplified, simplified.objects.countries).features.filter(f => f.id !== ANTARCTICA);

const alpha2 = (f) => {
    if (f.properties.code) return f.properties.code;
    if (f.properties.name === 'Kosovo') return 'XK';
    return f.id ? countries.numericToAlpha2(f.id) : undefined;
};

// Natural Earth folds some overseas territories into their country: split
// them out, so visiting Paris doesn't paint French Guiana. Each polygon far
// from the homeland goes to the nearest overseas territory listed.
const OVERSEAS = {
    FR: {
        home: ([lon, lat]) => lon > -6 && lon < 10 && lat > 41 && lat < 52,
        territories: { GF: [-53.1, 3.9], GP: [-61.55, 16.25], MQ: [-61.02, 14.64], RE: [55.53, -21.11], YT: [45.15, -12.83] },
    },
    NO: { home: ([, lat]) => lat < 72, territories: { SJ: [15.6, 78.2] } },
    NL: { home: ([lon]) => lon > 0, territories: { BQ: [-68.26, 12.2] } },
};
// Places the source has no outline for: shown as a dot where they are.
const DOT_ONLY = {
    GI: [-5.35, 36.14], BV: [3.4, -54.42], CC: [96.87, -12.16], CX: [105.69, -10.45],
    TK: [-171.85, -9.2], TV: [179.2, -8.52], UM: [166.62, 19.28],
};

const distance = ([a, b], [c, d]) => Math.hypot(a - c, b - d);
const splitOverseas = (features) => features.flatMap((f) => {
    const code = alpha2(f);
    const rule = OVERSEAS[code];
    if (!rule || f.geometry.type !== 'MultiPolygon') return [f];
    const parts = {};
    for (const polygon of f.geometry.coordinates) {
        const center = geoCentroid({ type: 'Polygon', coordinates: polygon });
        const target = rule.home(center)
            ? code
            : Object.entries(rule.territories).sort(([, a], [, b]) => distance(center, a) - distance(center, b))[0][0];
        (parts[target] ??= []).push(polygon);
    }
    return Object.entries(parts).map(([target, polygons]) => ({
        ...f,
        properties: { ...f.properties, code: target },
        geometry: { type: 'MultiPolygon', coordinates: polygons },
    }));
});

const projection = geoNaturalEarth1().fitWidth(WIDTH, { type: 'FeatureCollection', features: all });
const path = geoPath(projection).digits(1);
const [[, top], [, bottom]] = path.bounds({ type: 'FeatureCollection', features: all });
projection.translate([projection.translate()[0], projection.translate()[1] - top]);
const height = Math.ceil(bottom - top);

const shapes = {};
const skipped = [];
for (const f of splitOverseas(all)) {
    const code = alpha2(f);
    if (!code) {
        skipped.push(f.properties.name);
        continue;
    }
    const d = path(f);
    if (!d) continue;
    const shape = shapes[code] ?? { d: '', area: 0, largest: null };
    const area = path.area(f);
    shape.d += d;
    shape.area += area;
    if (!shape.largest || area > shape.largest.area) shape.largest = { area, feature: f };
    shapes[code] = shape;
}

const out = {};
for (const [code, shape] of Object.entries(shapes)) {
    out[code] = shape.area < TINY_AREA
        ? { d: shape.d, dot: path.centroid(shape.largest.feature).map(round) }
        : { d: shape.d };
}
for (const [code, lonLat] of Object.entries(DOT_ONLY)) {
    out[code] = { dot: projection(lonLat).map(round) };
}

fs.writeFileSync(OUTPUT, [
    '// Generated by shared/scripts/generateWorldMap.mjs from Natural Earth (public domain). Do not edit by hand.',
    `export const WORLD_MAP = Object.freeze(${JSON.stringify({ width: WIDTH, height, countries: out })});`,
    '',
].join('\n'));
console.log(`${Object.keys(out).length} countries written; skipped (no ISO code): ${skipped.join(', ')}`);
