import { normalizeSearchText } from "../normalizeSearchText.js";

// Country names for the passport stamps, generated once with Intl.DisplayNames
// (Node, full ICU) for the ISO codes in api/src/utils/countryCodes.js. Kept as
// data because the mobile JS engine (Hermes) has no Intl.DisplayNames.
export const COUNTRY_NAMES = Object.freeze({
  AD: { en: "Andorra", es: "Andorra", fr: "Andorre", it: "Andorra", de: "Andorra" },
  AE: { en: "United Arab Emirates", es: "Emiratos Árabes Unidos", fr: "Émirats arabes unis", it: "Emirati Arabi Uniti", de: "Vereinigte Arabische Emirate" },
  AF: { en: "Afghanistan", es: "Afganistán", fr: "Afghanistan", it: "Afghanistan", de: "Afghanistan" },
  AG: { en: "Antigua & Barbuda", es: "Antigua y Barbuda", fr: "Antigua-et-Barbuda", it: "Antigua e Barbuda", de: "Antigua und Barbuda" },
  AI: { en: "Anguilla", es: "Anguila", fr: "Anguilla", it: "Anguilla", de: "Anguilla" },
  AL: { en: "Albania", es: "Albania", fr: "Albanie", it: "Albania", de: "Albanien" },
  AM: { en: "Armenia", es: "Armenia", fr: "Arménie", it: "Armenia", de: "Armenien" },
  AO: { en: "Angola", es: "Angola", fr: "Angola", it: "Angola", de: "Angola" },
  AQ: { en: "Antarctica", es: "Antártida", fr: "Antarctique", it: "Antartide", de: "Antarktis" },
  AR: { en: "Argentina", es: "Argentina", fr: "Argentine", it: "Argentina", de: "Argentinien" },
  AS: { en: "American Samoa", es: "Samoa Americana", fr: "Samoa américaines", it: "Samoa Americane", de: "Amerikanisch-Samoa" },
  AT: { en: "Austria", es: "Austria", fr: "Autriche", it: "Austria", de: "Österreich" },
  AU: { en: "Australia", es: "Australia", fr: "Australie", it: "Australia", de: "Australien" },
  AW: { en: "Aruba", es: "Aruba", fr: "Aruba", it: "Aruba", de: "Aruba" },
  AX: { en: "Åland Islands", es: "Islas Aland", fr: "Îles Åland", it: "Isole Åland", de: "Ålandinseln" },
  AZ: { en: "Azerbaijan", es: "Azerbaiyán", fr: "Azerbaïdjan", it: "Azerbaigian", de: "Aserbaidschan" },
  BA: { en: "Bosnia & Herzegovina", es: "Bosnia y Herzegovina", fr: "Bosnie-Herzégovine", it: "Bosnia ed Erzegovina", de: "Bosnien und Herzegowina" },
  BB: { en: "Barbados", es: "Barbados", fr: "Barbade", it: "Barbados", de: "Barbados" },
  BD: { en: "Bangladesh", es: "Bangladés", fr: "Bangladesh", it: "Bangladesh", de: "Bangladesch" },
  BE: { en: "Belgium", es: "Bélgica", fr: "Belgique", it: "Belgio", de: "Belgien" },
  BF: { en: "Burkina Faso", es: "Burkina Faso", fr: "Burkina Faso", it: "Burkina Faso", de: "Burkina Faso" },
  BG: { en: "Bulgaria", es: "Bulgaria", fr: "Bulgarie", it: "Bulgaria", de: "Bulgarien" },
  BH: { en: "Bahrain", es: "Baréin", fr: "Bahreïn", it: "Bahrein", de: "Bahrain" },
  BI: { en: "Burundi", es: "Burundi", fr: "Burundi", it: "Burundi", de: "Burundi" },
  BJ: { en: "Benin", es: "Benín", fr: "Bénin", it: "Benin", de: "Benin" },
  BL: { en: "St. Barthélemy", es: "San Bartolomé", fr: "Saint-Barthélemy", it: "Saint-Barthélemy", de: "St. Barthélemy" },
  BM: { en: "Bermuda", es: "Bermudas", fr: "Bermudes", it: "Bermuda", de: "Bermuda" },
  BN: { en: "Brunei", es: "Brunéi", fr: "Brunei", it: "Brunei", de: "Brunei Darussalam" },
  BO: { en: "Bolivia", es: "Bolivia", fr: "Bolivie", it: "Bolivia", de: "Bolivien" },
  BQ: { en: "Caribbean Netherlands", es: "Caribe neerlandés", fr: "Pays-Bas caribéens", it: "Caraibi Olandesi", de: "Karibische Niederlande" },
  BR: { en: "Brazil", es: "Brasil", fr: "Brésil", it: "Brasile", de: "Brasilien" },
  BS: { en: "Bahamas", es: "Bahamas", fr: "Bahamas", it: "Bahamas", de: "Bahamas" },
  BT: { en: "Bhutan", es: "Bután", fr: "Bhoutan", it: "Bhutan", de: "Bhutan" },
  BV: { en: "Bouvet Island", es: "Isla Bouvet", fr: "Île Bouvet", it: "Isola Bouvet", de: "Bouvetinsel" },
  BW: { en: "Botswana", es: "Botsuana", fr: "Botswana", it: "Botswana", de: "Botsuana" },
  BY: { en: "Belarus", es: "Bielorrusia", fr: "Biélorussie", it: "Bielorussia", de: "Belarus" },
  BZ: { en: "Belize", es: "Belice", fr: "Belize", it: "Belize", de: "Belize" },
  CA: { en: "Canada", es: "Canadá", fr: "Canada", it: "Canada", de: "Kanada" },
  CC: { en: "Cocos (Keeling) Islands", es: "Islas Cocos", fr: "Îles Cocos", it: "Isole Cocos (Keeling)", de: "Kokosinseln" },
  CD: { en: "DR Congo", es: "R. D. del Congo", fr: "Congo-Kinshasa", it: "Congo - Kinshasa", de: "Kongo-Kinshasa" },
  CF: { en: "Central African Republic", es: "República Centroafricana", fr: "République centrafricaine", it: "Repubblica Centrafricana", de: "Zentralafrikanische Republik" },
  CG: { en: "Congo", es: "Congo", fr: "Congo-Brazzaville", it: "Congo-Brazzaville", de: "Kongo-Brazzaville" },
  CH: { en: "Switzerland", es: "Suiza", fr: "Suisse", it: "Svizzera", de: "Schweiz" },
  CI: { en: "Côte d’Ivoire", es: "Côte d’Ivoire", fr: "Côte d’Ivoire", it: "Costa d’Avorio", de: "Côte d’Ivoire" },
  CK: { en: "Cook Islands", es: "Islas Cook", fr: "Îles Cook", it: "Isole Cook", de: "Cookinseln" },
  CL: { en: "Chile", es: "Chile", fr: "Chili", it: "Cile", de: "Chile" },
  CM: { en: "Cameroon", es: "Camerún", fr: "Cameroun", it: "Camerun", de: "Kamerun" },
  CN: { en: "China", es: "China", fr: "Chine", it: "Cina", de: "China" },
  CO: { en: "Colombia", es: "Colombia", fr: "Colombie", it: "Colombia", de: "Kolumbien" },
  CR: { en: "Costa Rica", es: "Costa Rica", fr: "Costa Rica", it: "Costa Rica", de: "Costa Rica" },
  CU: { en: "Cuba", es: "Cuba", fr: "Cuba", it: "Cuba", de: "Kuba" },
  CV: { en: "Cape Verde", es: "Cabo Verde", fr: "Cap-Vert", it: "Capo Verde", de: "Cabo Verde" },
  CW: { en: "Curaçao", es: "Curazao", fr: "Curaçao", it: "Curaçao", de: "Curaçao" },
  CX: { en: "Christmas Island", es: "Isla de Navidad", fr: "Île Christmas", it: "Isola Christmas", de: "Weihnachtsinsel" },
  CY: { en: "Cyprus", es: "Chipre", fr: "Chypre", it: "Cipro", de: "Zypern" },
  CZ: { en: "Czechia", es: "Chequia", fr: "Tchéquie", it: "Cechia", de: "Tschechien" },
  DE: { en: "Germany", es: "Alemania", fr: "Allemagne", it: "Germania", de: "Deutschland" },
  DJ: { en: "Djibouti", es: "Yibuti", fr: "Djibouti", it: "Gibuti", de: "Dschibuti" },
  DK: { en: "Denmark", es: "Dinamarca", fr: "Danemark", it: "Danimarca", de: "Dänemark" },
  DM: { en: "Dominica", es: "Dominica", fr: "Dominique", it: "Dominica", de: "Dominica" },
  DO: { en: "Dominican Republic", es: "República Dominicana", fr: "République dominicaine", it: "Repubblica Dominicana", de: "Dominikanische Republik" },
  DZ: { en: "Algeria", es: "Argelia", fr: "Algérie", it: "Algeria", de: "Algerien" },
  EC: { en: "Ecuador", es: "Ecuador", fr: "Équateur", it: "Ecuador", de: "Ecuador" },
  EE: { en: "Estonia", es: "Estonia", fr: "Estonie", it: "Estonia", de: "Estland" },
  EG: { en: "Egypt", es: "Egipto", fr: "Égypte", it: "Egitto", de: "Ägypten" },
  EH: { en: "Western Sahara", es: "Sáhara Occidental", fr: "Sahara occidental", it: "Sahara Occidentale", de: "Westsahara" },
  ER: { en: "Eritrea", es: "Eritrea", fr: "Érythrée", it: "Eritrea", de: "Eritrea" },
  ES: { en: "Spain", es: "España", fr: "Espagne", it: "Spagna", de: "Spanien" },
  ET: { en: "Ethiopia", es: "Etiopía", fr: "Éthiopie", it: "Etiopia", de: "Äthiopien" },
  FI: { en: "Finland", es: "Finlandia", fr: "Finlande", it: "Finlandia", de: "Finnland" },
  FJ: { en: "Fiji", es: "Fiyi", fr: "Fidji", it: "Figi", de: "Fidschi" },
  FK: { en: "Falkland Islands", es: "Islas Malvinas", fr: "Îles Malouines", it: "Isole Falkland", de: "Falklandinseln" },
  FM: { en: "Micronesia", es: "Micronesia", fr: "Micronésie", it: "Micronesia", de: "Mikronesien" },
  FO: { en: "Faroe Islands", es: "Islas Feroe", fr: "Îles Féroé", it: "Isole Fær Øer", de: "Färöer" },
  FR: { en: "France", es: "Francia", fr: "France", it: "Francia", de: "Frankreich" },
  GA: { en: "Gabon", es: "Gabón", fr: "Gabon", it: "Gabon", de: "Gabun" },
  GB: { en: "United Kingdom", es: "Reino Unido", fr: "Royaume-Uni", it: "Regno Unito", de: "Vereinigtes Königreich" },
  GD: { en: "Grenada", es: "Granada", fr: "Grenade", it: "Grenada", de: "Grenada" },
  GE: { en: "Georgia", es: "Georgia", fr: "Géorgie", it: "Georgia", de: "Georgien" },
  GF: { en: "French Guiana", es: "Guayana Francesa", fr: "Guyane française", it: "Guyana Francese", de: "Französisch-Guayana" },
  GG: { en: "Guernsey", es: "Guernesey", fr: "Guernesey", it: "Guernsey", de: "Guernsey" },
  GH: { en: "Ghana", es: "Ghana", fr: "Ghana", it: "Ghana", de: "Ghana" },
  GI: { en: "Gibraltar", es: "Gibraltar", fr: "Gibraltar", it: "Gibilterra", de: "Gibraltar" },
  GL: { en: "Greenland", es: "Groenlandia", fr: "Groenland", it: "Groenlandia", de: "Grönland" },
  GM: { en: "Gambia", es: "Gambia", fr: "Gambie", it: "Gambia", de: "Gambia" },
  GN: { en: "Guinea", es: "Guinea", fr: "Guinée", it: "Guinea", de: "Guinea" },
  GP: { en: "Guadeloupe", es: "Guadalupe", fr: "Guadeloupe", it: "Guadalupa", de: "Guadeloupe" },
  GQ: { en: "Equatorial Guinea", es: "Guinea Ecuatorial", fr: "Guinée équatoriale", it: "Guinea Equatoriale", de: "Äquatorialguinea" },
  GR: { en: "Greece", es: "Grecia", fr: "Grèce", it: "Grecia", de: "Griechenland" },
  GS: { en: "South Georgia & South Sandwich Islands", es: "Islas Georgia del Sur y Sandwich del Sur", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", it: "Georgia del Sud e Sandwich Australi", de: "Südgeorgien und die Südlichen Sandwichinseln" },
  GT: { en: "Guatemala", es: "Guatemala", fr: "Guatemala", it: "Guatemala", de: "Guatemala" },
  GU: { en: "Guam", es: "Guam", fr: "Guam", it: "Guam", de: "Guam" },
  GW: { en: "Guinea-Bissau", es: "Guinea-Bisáu", fr: "Guinée-Bissau", it: "Guinea-Bissau", de: "Guinea-Bissau" },
  GY: { en: "Guyana", es: "Guyana", fr: "Guyana", it: "Guyana", de: "Guyana" },
  HK: { en: "Hong Kong", es: "Hong Kong", fr: "R.A.S. chinoise de Hong Kong", it: "RAS di Hong Kong", de: "Sonderverwaltungsregion Hongkong" },
  HM: { en: "Heard & McDonald Islands", es: "Islas Heard y McDonald", fr: "Îles Heard-et-MacDonald", it: "Isole Heard e McDonald", de: "Heard und McDonaldinseln" },
  HN: { en: "Honduras", es: "Honduras", fr: "Honduras", it: "Honduras", de: "Honduras" },
  HR: { en: "Croatia", es: "Croacia", fr: "Croatie", it: "Croazia", de: "Kroatien" },
  HT: { en: "Haiti", es: "Haití", fr: "Haïti", it: "Haiti", de: "Haiti" },
  HU: { en: "Hungary", es: "Hungría", fr: "Hongrie", it: "Ungheria", de: "Ungarn" },
  ID: { en: "Indonesia", es: "Indonesia", fr: "Indonésie", it: "Indonesia", de: "Indonesien" },
  IE: { en: "Ireland", es: "Irlanda", fr: "Irlande", it: "Irlanda", de: "Irland" },
  IL: { en: "Israel", es: "Israel", fr: "Israël", it: "Israele", de: "Israel" },
  IM: { en: "Isle of Man", es: "Isla de Man", fr: "Île de Man", it: "Isola di Man", de: "Isle of Man" },
  IN: { en: "India", es: "India", fr: "Inde", it: "India", de: "Indien" },
  IO: { en: "British Indian Ocean Territory", es: "Territorio Británico del Océano Índico", fr: "Territoire britannique de l’océan Indien", it: "Territorio Britannico dell’Oceano Indiano", de: "Britisches Territorium im Indischen Ozean" },
  IQ: { en: "Iraq", es: "Irak", fr: "Irak", it: "Iraq", de: "Irak" },
  IR: { en: "Iran", es: "Irán", fr: "Iran", it: "Iran", de: "Iran" },
  IS: { en: "Iceland", es: "Islandia", fr: "Islande", it: "Islanda", de: "Island" },
  IT: { en: "Italy", es: "Italia", fr: "Italie", it: "Italia", de: "Italien" },
  JE: { en: "Jersey", es: "Jersey", fr: "Jersey", it: "Jersey", de: "Jersey" },
  JM: { en: "Jamaica", es: "Jamaica", fr: "Jamaïque", it: "Giamaica", de: "Jamaika" },
  JO: { en: "Jordan", es: "Jordania", fr: "Jordanie", it: "Giordania", de: "Jordanien" },
  JP: { en: "Japan", es: "Japón", fr: "Japon", it: "Giappone", de: "Japan" },
  KE: { en: "Kenya", es: "Kenia", fr: "Kenya", it: "Kenya", de: "Kenia" },
  KG: { en: "Kyrgyzstan", es: "Kirguistán", fr: "Kirghizstan", it: "Kirghizistan", de: "Kirgisistan" },
  KH: { en: "Cambodia", es: "Camboya", fr: "Cambodge", it: "Cambogia", de: "Kambodscha" },
  KI: { en: "Kiribati", es: "Kiribati", fr: "Kiribati", it: "Kiribati", de: "Kiribati" },
  KM: { en: "Comoros", es: "Comoras", fr: "Comores", it: "Comore", de: "Komoren" },
  KN: { en: "St. Kitts & Nevis", es: "San Cristóbal y Nieves", fr: "Saint-Christophe-et-Niévès", it: "Saint Kitts e Nevis", de: "St. Kitts und Nevis" },
  KP: { en: "North Korea", es: "Corea del Norte", fr: "Corée du Nord", it: "Corea del Nord", de: "Nordkorea" },
  KR: { en: "South Korea", es: "Corea del Sur", fr: "Corée du Sud", it: "Corea del Sud", de: "Südkorea" },
  KW: { en: "Kuwait", es: "Kuwait", fr: "Koweït", it: "Kuwait", de: "Kuwait" },
  KY: { en: "Cayman Islands", es: "Islas Caimán", fr: "Îles Caïmans", it: "Isole Cayman", de: "Kaimaninseln" },
  KZ: { en: "Kazakhstan", es: "Kazajistán", fr: "Kazakhstan", it: "Kazakistan", de: "Kasachstan" },
  LA: { en: "Laos", es: "Laos", fr: "Laos", it: "Laos", de: "Laos" },
  LB: { en: "Lebanon", es: "Líbano", fr: "Liban", it: "Libano", de: "Libanon" },
  LC: { en: "St. Lucia", es: "Santa Lucía", fr: "Sainte-Lucie", it: "Saint Lucia", de: "St. Lucia" },
  LI: { en: "Liechtenstein", es: "Liechtenstein", fr: "Liechtenstein", it: "Liechtenstein", de: "Liechtenstein" },
  LK: { en: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka", it: "Sri Lanka", de: "Sri Lanka" },
  LR: { en: "Liberia", es: "Liberia", fr: "Liberia", it: "Liberia", de: "Liberia" },
  LS: { en: "Lesotho", es: "Lesoto", fr: "Lesotho", it: "Lesotho", de: "Lesotho" },
  LT: { en: "Lithuania", es: "Lituania", fr: "Lituanie", it: "Lituania", de: "Litauen" },
  LU: { en: "Luxembourg", es: "Luxemburgo", fr: "Luxembourg", it: "Lussemburgo", de: "Luxemburg" },
  LV: { en: "Latvia", es: "Letonia", fr: "Lettonie", it: "Lettonia", de: "Lettland" },
  LY: { en: "Libya", es: "Libia", fr: "Libye", it: "Libia", de: "Libyen" },
  MA: { en: "Morocco", es: "Marruecos", fr: "Maroc", it: "Marocco", de: "Marokko" },
  MC: { en: "Monaco", es: "Mónaco", fr: "Monaco", it: "Monaco", de: "Monaco" },
  MD: { en: "Moldova", es: "Moldavia", fr: "Moldavie", it: "Moldavia", de: "Republik Moldau" },
  ME: { en: "Montenegro", es: "Montenegro", fr: "Monténégro", it: "Montenegro", de: "Montenegro" },
  MF: { en: "St. Martin", es: "San Martín", fr: "Saint-Martin", it: "Saint Martin", de: "St. Martin" },
  MG: { en: "Madagascar", es: "Madagascar", fr: "Madagascar", it: "Madagascar", de: "Madagaskar" },
  MH: { en: "Marshall Islands", es: "Islas Marshall", fr: "Îles Marshall", it: "Isole Marshall", de: "Marshallinseln" },
  MK: { en: "North Macedonia", es: "Macedonia del Norte", fr: "Macédoine du Nord", it: "Macedonia del Nord", de: "Nordmazedonien" },
  ML: { en: "Mali", es: "Mali", fr: "Mali", it: "Mali", de: "Mali" },
  MM: { en: "Myanmar", es: "Myanmar", fr: "Myanmar (Birmanie)", it: "Myanmar (Birmania)", de: "Myanmar" },
  MN: { en: "Mongolia", es: "Mongolia", fr: "Mongolie", it: "Mongolia", de: "Mongolei" },
  MO: { en: "Macao", es: "Macao", fr: "R.A.S. chinoise de Macao", it: "RAS di Macao", de: "Sonderverwaltungsregion Macau" },
  MP: { en: "Northern Mariana Islands", es: "Islas Marianas del Norte", fr: "Îles Mariannes du Nord", it: "Isole Marianne Settentrionali", de: "Nördliche Marianen" },
  MQ: { en: "Martinique", es: "Martinica", fr: "Martinique", it: "Martinica", de: "Martinique" },
  MR: { en: "Mauritania", es: "Mauritania", fr: "Mauritanie", it: "Mauritania", de: "Mauretanien" },
  MS: { en: "Montserrat", es: "Montserrat", fr: "Montserrat", it: "Montserrat", de: "Montserrat" },
  MT: { en: "Malta", es: "Malta", fr: "Malte", it: "Malta", de: "Malta" },
  MU: { en: "Mauritius", es: "Mauricio", fr: "Maurice", it: "Mauritius", de: "Mauritius" },
  MV: { en: "Maldives", es: "Maldivas", fr: "Maldives", it: "Maldive", de: "Malediven" },
  MW: { en: "Malawi", es: "Malaui", fr: "Malawi", it: "Malawi", de: "Malawi" },
  MX: { en: "Mexico", es: "México", fr: "Mexique", it: "Messico", de: "Mexiko" },
  MY: { en: "Malaysia", es: "Malasia", fr: "Malaisie", it: "Malaysia", de: "Malaysia" },
  MZ: { en: "Mozambique", es: "Mozambique", fr: "Mozambique", it: "Mozambico", de: "Mosambik" },
  NA: { en: "Namibia", es: "Namibia", fr: "Namibie", it: "Namibia", de: "Namibia" },
  NC: { en: "New Caledonia", es: "Nueva Caledonia", fr: "Nouvelle-Calédonie", it: "Nuova Caledonia", de: "Neukaledonien" },
  NE: { en: "Niger", es: "Níger", fr: "Niger", it: "Niger", de: "Niger" },
  NF: { en: "Norfolk Island", es: "Isla Norfolk", fr: "Île Norfolk", it: "Isola Norfolk", de: "Norfolkinsel" },
  NG: { en: "Nigeria", es: "Nigeria", fr: "Nigeria", it: "Nigeria", de: "Nigeria" },
  NI: { en: "Nicaragua", es: "Nicaragua", fr: "Nicaragua", it: "Nicaragua", de: "Nicaragua" },
  NL: { en: "Netherlands", es: "Países Bajos", fr: "Pays-Bas", it: "Paesi Bassi", de: "Niederlande" },
  NO: { en: "Norway", es: "Noruega", fr: "Norvège", it: "Norvegia", de: "Norwegen" },
  NP: { en: "Nepal", es: "Nepal", fr: "Népal", it: "Nepal", de: "Nepal" },
  NR: { en: "Nauru", es: "Nauru", fr: "Nauru", it: "Nauru", de: "Nauru" },
  NU: { en: "Niue", es: "Niue", fr: "Niue", it: "Niue", de: "Niue" },
  NZ: { en: "New Zealand", es: "Nueva Zelanda", fr: "Nouvelle-Zélande", it: "Nuova Zelanda", de: "Neuseeland" },
  OM: { en: "Oman", es: "Omán", fr: "Oman", it: "Oman", de: "Oman" },
  PA: { en: "Panama", es: "Panamá", fr: "Panama", it: "Panama", de: "Panama" },
  PE: { en: "Peru", es: "Perú", fr: "Pérou", it: "Perù", de: "Peru" },
  PF: { en: "French Polynesia", es: "Polinesia Francesa", fr: "Polynésie française", it: "Polinesia Francese", de: "Französisch-Polynesien" },
  PG: { en: "Papua New Guinea", es: "Papúa Nueva Guinea", fr: "Papouasie-Nouvelle-Guinée", it: "Papua Nuova Guinea", de: "Papua-Neuguinea" },
  PH: { en: "Philippines", es: "Filipinas", fr: "Philippines", it: "Filippine", de: "Philippinen" },
  PK: { en: "Pakistan", es: "Pakistán", fr: "Pakistan", it: "Pakistan", de: "Pakistan" },
  PL: { en: "Poland", es: "Polonia", fr: "Pologne", it: "Polonia", de: "Polen" },
  PM: { en: "St. Pierre & Miquelon", es: "San Pedro y Miquelón", fr: "Saint-Pierre-et-Miquelon", it: "Saint-Pierre e Miquelon", de: "St. Pierre und Miquelon" },
  PN: { en: "Pitcairn Islands", es: "Islas Pitcairn", fr: "Îles Pitcairn", it: "Isole Pitcairn", de: "Pitcairninseln" },
  PR: { en: "Puerto Rico", es: "Puerto Rico", fr: "Porto Rico", it: "Portorico", de: "Puerto Rico" },
  PS: { en: "Palestine", es: "Palestina", fr: "Territoires palestiniens", it: "Territori Palestinesi", de: "Palästinensische Autonomiegebiete" },
  PT: { en: "Portugal", es: "Portugal", fr: "Portugal", it: "Portogallo", de: "Portugal" },
  PW: { en: "Palau", es: "Palaos", fr: "Palaos", it: "Palau", de: "Palau" },
  PY: { en: "Paraguay", es: "Paraguay", fr: "Paraguay", it: "Paraguay", de: "Paraguay" },
  QA: { en: "Qatar", es: "Catar", fr: "Qatar", it: "Qatar", de: "Katar" },
  RE: { en: "Réunion", es: "Reunión", fr: "La Réunion", it: "Riunione", de: "Réunion" },
  RO: { en: "Romania", es: "Rumanía", fr: "Roumanie", it: "Romania", de: "Rumänien" },
  RS: { en: "Serbia", es: "Serbia", fr: "Serbie", it: "Serbia", de: "Serbien" },
  RU: { en: "Russia", es: "Rusia", fr: "Russie", it: "Russia", de: "Russland" },
  RW: { en: "Rwanda", es: "Ruanda", fr: "Rwanda", it: "Ruanda", de: "Ruanda" },
  SA: { en: "Saudi Arabia", es: "Arabia Saudí", fr: "Arabie saoudite", it: "Arabia Saudita", de: "Saudi-Arabien" },
  SB: { en: "Solomon Islands", es: "Islas Salomón", fr: "Îles Salomon", it: "Isole Salomone", de: "Salomonen" },
  SC: { en: "Seychelles", es: "Seychelles", fr: "Seychelles", it: "Seychelles", de: "Seychellen" },
  SD: { en: "Sudan", es: "Sudán", fr: "Soudan", it: "Sudan", de: "Sudan" },
  SE: { en: "Sweden", es: "Suecia", fr: "Suède", it: "Svezia", de: "Schweden" },
  SG: { en: "Singapore", es: "Singapur", fr: "Singapour", it: "Singapore", de: "Singapur" },
  SH: { en: "St. Helena", es: "Santa Elena", fr: "Sainte-Hélène", it: "Sant’Elena", de: "St. Helena" },
  SI: { en: "Slovenia", es: "Eslovenia", fr: "Slovénie", it: "Slovenia", de: "Slowenien" },
  SJ: { en: "Svalbard & Jan Mayen", es: "Svalbard y Jan Mayen", fr: "Svalbard et Jan Mayen", it: "Svalbard e Jan Mayen", de: "Spitzbergen und Jan Mayen" },
  SK: { en: "Slovakia", es: "Eslovaquia", fr: "Slovaquie", it: "Slovacchia", de: "Slowakei" },
  SL: { en: "Sierra Leone", es: "Sierra Leona", fr: "Sierra Leone", it: "Sierra Leone", de: "Sierra Leone" },
  SM: { en: "San Marino", es: "San Marino", fr: "Saint-Marin", it: "San Marino", de: "San Marino" },
  SN: { en: "Senegal", es: "Senegal", fr: "Sénégal", it: "Senegal", de: "Senegal" },
  SO: { en: "Somalia", es: "Somalia", fr: "Somalie", it: "Somalia", de: "Somalia" },
  SR: { en: "Suriname", es: "Surinam", fr: "Suriname", it: "Suriname", de: "Suriname" },
  SS: { en: "South Sudan", es: "Sudán del Sur", fr: "Soudan du Sud", it: "Sud Sudan", de: "Südsudan" },
  ST: { en: "São Tomé & Príncipe", es: "Santo Tomé y Príncipe", fr: "Sao Tomé-et-Principe", it: "São Tomé e Príncipe", de: "São Tomé und Príncipe" },
  SV: { en: "El Salvador", es: "El Salvador", fr: "Salvador", it: "El Salvador", de: "El Salvador" },
  SX: { en: "Sint Maarten", es: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)", it: "Sint Maarten", de: "Sint Maarten" },
  SY: { en: "Syria", es: "Siria", fr: "Syrie", it: "Siria", de: "Syrien" },
  SZ: { en: "Eswatini", es: "Esuatini", fr: "Eswatini", it: "Eswatini", de: "Eswatini" },
  TC: { en: "Turks & Caicos Islands", es: "Islas Turcas y Caicos", fr: "Îles Turques-et-Caïques", it: "Isole Turks e Caicos", de: "Turks- und Caicosinseln" },
  TD: { en: "Chad", es: "Chad", fr: "Tchad", it: "Ciad", de: "Tschad" },
  TF: { en: "French Southern Territories", es: "Territorios Australes Franceses", fr: "Terres australes françaises", it: "Terre Australi Francesi", de: "Französische Süd- und Antarktisgebiete" },
  TG: { en: "Togo", es: "Togo", fr: "Togo", it: "Togo", de: "Togo" },
  TH: { en: "Thailand", es: "Tailandia", fr: "Thaïlande", it: "Thailandia", de: "Thailand" },
  TJ: { en: "Tajikistan", es: "Tayikistán", fr: "Tadjikistan", it: "Tagikistan", de: "Tadschikistan" },
  TK: { en: "Tokelau", es: "Tokelau", fr: "Tokelau", it: "Tokelau", de: "Tokelau" },
  TL: { en: "Timor-Leste", es: "Timor-Leste", fr: "Timor oriental", it: "Timor Est", de: "Timor-Leste" },
  TM: { en: "Turkmenistan", es: "Turkmenistán", fr: "Turkménistan", it: "Turkmenistan", de: "Turkmenistan" },
  TN: { en: "Tunisia", es: "Túnez", fr: "Tunisie", it: "Tunisia", de: "Tunesien" },
  TO: { en: "Tonga", es: "Tonga", fr: "Tonga", it: "Tonga", de: "Tonga" },
  TR: { en: "Türkiye", es: "Turquía", fr: "Turquie", it: "Turchia", de: "Türkei" },
  TT: { en: "Trinidad & Tobago", es: "Trinidad y Tobago", fr: "Trinité-et-Tobago", it: "Trinidad e Tobago", de: "Trinidad und Tobago" },
  TV: { en: "Tuvalu", es: "Tuvalu", fr: "Tuvalu", it: "Tuvalu", de: "Tuvalu" },
  TW: { en: "Taiwan", es: "Taiwán", fr: "Taïwan", it: "Taiwan", de: "Taiwan" },
  TZ: { en: "Tanzania", es: "Tanzania", fr: "Tanzanie", it: "Tanzania", de: "Tansania" },
  UA: { en: "Ukraine", es: "Ucrania", fr: "Ukraine", it: "Ucraina", de: "Ukraine" },
  UG: { en: "Uganda", es: "Uganda", fr: "Ouganda", it: "Uganda", de: "Uganda" },
  UM: { en: "U.S. Outlying Islands", es: "Islas menores alejadas de EE. UU.", fr: "Îles mineures éloignées des États-Unis", it: "Isole Minori Esterne degli Stati Uniti", de: "Amerikanische Überseeinseln" },
  US: { en: "United States", es: "Estados Unidos", fr: "États-Unis", it: "Stati Uniti", de: "Vereinigte Staaten" },
  UY: { en: "Uruguay", es: "Uruguay", fr: "Uruguay", it: "Uruguay", de: "Uruguay" },
  UZ: { en: "Uzbekistan", es: "Uzbekistán", fr: "Ouzbékistan", it: "Uzbekistan", de: "Usbekistan" },
  VA: { en: "Vatican City", es: "Ciudad del Vaticano", fr: "État de la Cité du Vatican", it: "Città del Vaticano", de: "Vatikanstadt" },
  VC: { en: "St. Vincent & Grenadines", es: "San Vicente y las Granadinas", fr: "Saint-Vincent-et-les Grenadines", it: "Saint Vincent e Grenadine", de: "St. Vincent und die Grenadinen" },
  VE: { en: "Venezuela", es: "Venezuela", fr: "Venezuela", it: "Venezuela", de: "Venezuela" },
  VG: { en: "British Virgin Islands", es: "Islas Vírgenes Británicas", fr: "Îles Vierges britanniques", it: "Isole Vergini Britanniche", de: "Britische Jungferninseln" },
  VI: { en: "U.S. Virgin Islands", es: "Islas Vírgenes de EE. UU.", fr: "Îles Vierges des États-Unis", it: "Isole Vergini Americane", de: "Amerikanische Jungferninseln" },
  VN: { en: "Vietnam", es: "Vietnam", fr: "Viêt Nam", it: "Vietnam", de: "Vietnam" },
  VU: { en: "Vanuatu", es: "Vanuatu", fr: "Vanuatu", it: "Vanuatu", de: "Vanuatu" },
  WF: { en: "Wallis & Futuna", es: "Wallis y Futuna", fr: "Wallis-et-Futuna", it: "Wallis e Futuna", de: "Wallis und Futuna" },
  WS: { en: "Samoa", es: "Samoa", fr: "Samoa", it: "Samoa", de: "Samoa" },
  XK: { en: "Kosovo", es: "Kosovo", fr: "Kosovo", it: "Kosovo", de: "Kosovo" },
  YE: { en: "Yemen", es: "Yemen", fr: "Yémen", it: "Yemen", de: "Jemen" },
  YT: { en: "Mayotte", es: "Mayotte", fr: "Mayotte", it: "Mayotte", de: "Mayotte" },
  ZA: { en: "South Africa", es: "Sudáfrica", fr: "Afrique du Sud", it: "Sudafrica", de: "Südafrika" },
  ZM: { en: "Zambia", es: "Zambia", fr: "Zambie", it: "Zambia", de: "Sambia" },
  ZW: { en: "Zimbabwe", es: "Zimbabue", fr: "Zimbabwe", it: "Zimbabwe", de: "Simbabwe" },
});

// Regional-indicator emoji flag from an ISO code ("ES" -> 🇪🇸).
export const countryFlag = (code) => String.fromCodePoint(
    ...code.toUpperCase().split("").map(letter => 0x1f1e6 + letter.charCodeAt(0) - 65)
);

export const countryCodesByName = (language) => Object.keys(COUNTRY_NAMES)
    .sort((a, b) => countryName(a, language).localeCompare(countryName(b, language), language));

export const searchCountryCodes = (query, language) => {
    const term = normalizeSearchText(query.trim());
    const codes = countryCodesByName(language);
    if (!term) return codes;
    // Accent-insensitive, so "japon" finds Japón.
    return codes.filter(code => normalizeSearchText(countryName(code, language)).includes(term) || code.toLowerCase() === term);
};

export const countryName = (code, language) => {
    const names = COUNTRY_NAMES[code];
    if (!names) return code;
    return names[language?.split("-")[0]] ?? names.en;
};

const STAMP_COLORS = ['#B23A48', '#1A535C', '#E8743B', '#3D5A80', '#6B4C9A', '#2A9D8F', '#8C5E2A'];
const MAX_STAMP_ROTATION_DEG = 6;

// Each country always gets the same ink colour and tilt, so a passport looks
// hand-stamped yet stays identical between visits and devices.
export const passportStampStyle = (code) => {
    const hash = [...code].reduce((sum, letter, index) => sum + letter.charCodeAt(0) * (index + 7), 0);
    return {
        color: STAMP_COLORS[hash % STAMP_COLORS.length],
        rotation: (hash % (MAX_STAMP_ROTATION_DEG * 2 + 1)) - MAX_STAMP_ROTATION_DEG,
    };
};
