# name: Ping API health-check

# on:
#   schedule:
#     - cron: '*/10 * * * *'

# jobs:
#   ping-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Curl health-check endpoint
#         run: curl -fsS --retry 3 https://tfm-eta.vercel.app/api/health-check
